### ISSUE TITLE
riscv: Build failure in commit b2214529735a

### ISSUE THREAD

**Issue by WangJia-UR** [RVCK-Project/kernel-6.6#84]
编译 commit `b2214529735a61b93960f43e4235706329cdbe09` 版本时失败。

Error message:
```
arch/riscv/kernel/machine_kexec_file.c: In function 'load_extra_segments':
arch/riscv/kernel/machine_kexec_file.c:298:17: error: implicit declaration of function 'kexec_dprintk' [-Wimplicit-function-declaration]
  298 |                 kexec_dprintk("Loaded elf core header at 0x%lx bufsz=0x%lx memsz=0x%lx\n",
      |                 ^~~~~~~~~~~~~
```

需要backport kexec_dpritnk相关patch：https://lore.kernel.org/all/20231213055747.61826-1-bhe@redhat.com/

**Comment by WangJia-UR** [comment]
已由pr #78 修复
